version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:3.13.4-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  some-net:
    driver: bridge
